Initialized scraper for Wegmans
livgust/covid-vaccine-scrapers pull request #136
Opened 2021-03-09 03:45 UTC by zpeyton

This will notify us via slack webhook if there are possible appointments.

2021-03-09 14:11 UTC, iann approved these changes
looks good! nice touch removing the `waitFor`

2021-03-09 15:37 UTC, livgust commented
#21

2021-03-09 17:22 UTC, livgust requested changes
Looks good but we're leaving in the fields getStartedBtn, massLinkXPath, and noAppointments which I think should be removed from the response structure.

2021-03-10 02:26 UTC, livgust approved these changes

2021-03-10 02:26 UTC, merged