MAImmunization: Check to see if the signUpLink has real availability
livgust/covid-vaccine-scrapers pull request #189
Opened 2021-03-27 13:01 UTC by harcod

MAImmunizations.org frequently reports available slots on the "search page" only to show _no availability_ after clicking the signup link.

By checking the contents of the signUpLink itself, we can see if the user can actually book a slot.

```
<div class="danger-alert">
       Clinic does not have any appointment slots available.
</div>
```

2021-03-27 13:05 UTC, harcod commented
There is currently no location with _real availability_ so I'm assuming that **danger-alert** doesn't actually appear on _good pages_.

2021-03-27 13:50 UTC, livgust requested changes
This is AWESOME. I'm on my phone so can't test, but sometimes you can go in and it doesn't show the banner because you can sign up for a wait list. Do you think we could check for that too?

2021-03-27 21:00 UTC, harcod commented
I'd keep it simple for a first pass and just look for this danger-alert.  If there is a wait-list, then at least the person has something actionable to do.

2021-03-29 21:41 UTC, tkjones117 approved these changes
@harcod The code looks good. Lmk if there's anything you want me to test out on my end (currently there aren't slots with "broken links").

2021-03-29 21:44 UTC, harcod commented
> @harcod The code looks good. Lmk if there's anything you want me to test out on my end (currently there aren't slots with "broken links").

@tkjones117 Usually all of the slots are "danger-alert" links.  I did see a location with real available slots a few minutes ago and ran the scraper.  It correctly inserted the **signUpLink** into the json!

2021-03-30 02:37 UTC, iann approved these changes
code works locally and set the sign up link to null as expected.

2021-03-30 02:41 UTC, livgust approved these changes

2021-03-30 02:41 UTC, merged