Upload a datestamped result set to S3
livgust/covid-vaccine-scrapers pull request #4
Opened 2021-02-12 18:50 UTC by johnhawkinson

We could probably architect this better, but this should do for now.

2021-02-12 20:24 UTC, carloshgaray approved these changes
sgtm let's have a sync late next week on a design session

2021-02-12 20:38 UTC, livgust requested changes

2021-02-12 20:38 UTC, livgust commented on main.js
> +			const results = await new Promise((resolve, reject) => {
@carloshgaray he added a second promise so it'll write to data.json and also the timestamped file.
@johnhawkinson Is there a reason you're returning the results of the initial promise? I don't think we actually care about the return value here.

2021-02-12 20:49 UTC, johnhawkinson commented on main.js
> +			const results = await new Promise((resolve, reject) => {
I was just trying to make the most surgical change possible without affecting anything else.
You were returning the data.json result before, so I wanted to keep that.

2021-02-12 21:36 UTC, livgust commented on main.js
> +			const results = await new Promise((resolve, reject) => {
LGTM. I'll test, merge, and upload to Lambda when the kids go to bed. Then I'll look into making the S3 bucket public so people can use these files for data analytics and such.

2021-02-13 03:07 UTC, livgust approved these changes

2021-02-13 03:08 UTC, livgust commented
Merging to master, then going to zip to Lambda for a test run

2021-02-13 03:08 UTC, merged

2021-02-13 03:35 UTC, livgust commented
Looks good but file name has a colon: data-2021-02-13T03:30Z.json

2021-02-13 03:37 UTC, johnhawkinson commented
Bah humbug. Colons aren't illegal in most OS's filenames, but they are a really bad idea.
I assume you're saying we should change it…